### ISSUE TITLE
 GetKey WARNING: Download key Failed - Khoa khong du du lieu.

### ISSUE THREAD

**Issue by gago2627** [NguyenKhong/Download_Edumall#1]
2019-03-18 17:35:51,417 GetKey WARNING: Download key Failed - Khoa khong du du lieu.
, không lấy key được bác ơi , mình thử cả giải mã (2) , , cũng k đc nốt

**Comment by NguyenKhong** [comment]
Lâu rồi cũng không vào edumall nên không rõ. Với lại đang phát triển phiên bản mới do bên edumall thay đổi. Bạn thông cảm.

**Comment by NguyenKhong** [comment]
Bạn tạm dùng bên này : https://github.com/NguyenKhong/Download_Edumall_beta
